#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-express-deployment
spec:
  selector:
    matchLabels:
      app: kafka-express-server
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-express-server
    spec:
      containers:
      - name: kafka-express-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/harlock024/kafka-express:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kafka-express-service
  name: kafka-express-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: kafka-express-server
  type: NodePort
