#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-express-deployment
spec:
  selector:
    matchLabels:
      app: kafka-express-server
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-express-server
    spec:
      containers:
      - name: kafka-express-container
        image: docker.io/harlock024/kafka-express:c0f4c2c2b4d217d30c1c2e8584ba968049c79935
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kafka-express-service
  name: kafka-express-service
spec:
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30080
  selector:
    app: kafka-express-server
  type: NodePort
